services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupalpassword

  web:
    image: drupal:11-apache
    volumes:
      - ./drupal/web/modules:/var/www/html/modules
      - ./drupal/web/profiles:/var/www/html/profiles
      - ./drupal/web/themes:/var/www/html/themes
      - ./drupal/web/sites:/var/www/html/sites
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupalpassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
volumes:
  db_data:
